### ISSUE TITLE
'java.lang.NullPointerException: null' if UserRepository.defaultAdmin returns null

### ISSUE THREAD

**Issue by fedotxxl** [restx/restx#181]
```
Caused by: java.lang.NullPointerException: null
	at restx.security.StdUserService.findUserByName(StdUserService.java:29) ~[restx-security-basic-0.34.jar:na]
	at restx.security.StdBasicPrincipalAuthenticator.findByName(StdBasicPrincipalAuthenticator.java:22) ~[restx-security-basic-0.34.jar:na]
```

Here is code from StdUserService:

```
public Optional<U> findUserByName(String name) {
        Optional<U> user = repository.findUserByName(name);
        if (!user.isPresent()) {
            U defaultAdmin = repository.defaultAdmin();
            if (defaultAdmin.getName().equals(name) && !repository.isAdminDefined()) {
                return Optional.of(defaultAdmin);
            }
        }
        return user;
    }
```

Shouldn't it be ` !repository.isAdminDefined() && defaultAdmin.getName().equals(name)` ?

**Comment by xhanin** [comment]
Indeed, using `!repository.isAdminDefined() && defaultAdmin.getName().equals(name)` would allow to avoid defining a default admin. But it would also mean that `repository.isAdminDefined()` would be potentially called more often (for any user and not only for admin), which could put more pressure on the repository. Not a big deal, but I think we can deal with a simple null check: `defaultAdmin != null && defaultAdmin.getName().equals(name) && !repository.isAdminDefined()`
