### ISSUE TITLE
How to disable lazy initialization for component?

### ISSUE THREAD

**Issue by fedotxxl** [restx/restx#202]
Hello. I wanna create `Bootstrap` component which will do some job on app start. Restx doesn't initialize it because it's not injected. Can I disable lazy initialization for single component?

**Comment by fcamblor** [comment]
For questions, could you use google group instead of github which is more likely to track issues & improvements ?

That being said, did you try to make your `Bootstrap` component implement `Autostartable` ? (see [here](http://restx.io/docs/ref-lifecycle.html#toc8))

**Comment by fedotxxl** [comment]
It's funny. Looks like I was right using github. I implemented AutoStartable interface. Now I'm getting following exception:
```
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of restx/classloader/CompilationManager$11) previously initiated loading for a different type with name "com/stackcare/site/user/User"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_40]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_40]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[na:1.8.0_40]
	at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:141) ~[restx-classloader-0.34.jar:na]
	at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:128) ~[restx-classloader-0.34.jar:na]
	at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:109) ~[restx-classloader-0.34.jar:na]
	at restx.classloader.HotReloadingClassLoader.loadClass(HotReloadingClassLoader.java:87) ~[restx-classloader-0.34.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
	at com.stackcare.site.user.UserDao.getUserByMail(UserDao.java:29) ~[site/:na]
	at com.stackcare.site.security.StackUserRepository.findUserByName(StackUserRepository.java:25) ~[site/:na]
	at restx.security.StdUserService.findUserByName(StdUserService.java:26) ~[restx-security-basic-0.34.jar:na]
	at restx.security.StdBasicPrincipalAuthenticator.findByName(StdBasicPrincipalAuthenticator.java:22) ~[restx-security-basic-0.34.jar:na]
	at restx.security.BasicSecurityModule$1.apply(BasicSecurityModule.java:21) ~[restx-security-basic-0.34.jar:na]
	at restx.security.BasicSecurityModule$1.apply(BasicSecurityModule.java:18) ~[restx-security-basic-0.34.jar:na]
	at restx.security.DefaultSessionDefinitionEntry.getValueForId(DefaultSessionDefinitionEntry.java:27) ~[restx-core-0.34.jar:na]
	at restx.security.GuavaEntryCacheManager$1.load(GuavaEntryCacheManager.java:37) ~[restx-core-0.34.jar:na]
	at restx.security.GuavaEntryCacheManager$1.load(GuavaEntryCacheManager.java:34) ~[restx-core-0.34.jar:na]
```

My Bootstrap component don't even use `com.stackcare.site.user.User` class.
