### ISSUE TITLE
Adding AutoStartable component leads to "loader constraint violation" exception

### ISSUE THREAD

**Issue by fedotxxl** [restx/restx#203]
Hello
I implemented AutoStartable interface. Now I'm getting following exception:
```
Caused by: java.lang.LinkageError: loader constraint violation: loader (instance of restx/classloader/CompilationManager$11) previously initiated loading for a different type with name "com/stackcare/site/user/User"
	at java.lang.ClassLoader.defineClass1(Native Method) ~[na:1.8.0_40]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) ~[na:1.8.0_40]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642) ~[na:1.8.0_40]
	at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:141) ~[restx-classloader-0.34.jar:na]
	at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:128) ~[restx-classloader-0.34.jar:na]
	at restx.classloader.HotReloadingClassLoader.defineClass(HotReloadingClassLoader.java:109) ~[restx-classloader-0.34.jar:na]
	at restx.classloader.HotReloadingClassLoader.loadClass(HotReloadingClassLoader.java:87) ~[restx-classloader-0.34.jar:na]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
	at com.stackcare.site.user.UserDao.getUserByMail(UserDao.java:29) ~[site/:na]
	at com.stackcare.site.security.StackUserRepository.findUserByName(StackUserRepository.java:25) ~[site/:na]
	at restx.security.StdUserService.findUserByName(StdUserService.java:26) ~[restx-security-basic-0.34.jar:na]
	at restx.security.StdBasicPrincipalAuthenticator.findByName(StdBasicPrincipalAuthenticator.java:22) ~[restx-security-basic-0.34.jar:na]
	at restx.security.BasicSecurityModule$1.apply(BasicSecurityModule.java:21) ~[restx-security-basic-0.34.jar:na]
	at restx.security.BasicSecurityModule$1.apply(BasicSecurityModule.java:18) ~[restx-security-basic-0.34.jar:na]
	at restx.security.DefaultSessionDefinitionEntry.getValueForId(DefaultSessionDefinitionEntry.java:27) ~[restx-core-0.34.jar:na]
	at restx.security.GuavaEntryCacheManager$1.load(GuavaEntryCacheManager.java:37) ~[restx-core-0.34.jar:na]
	at restx.security.GuavaEntryCacheManager$1.load(GuavaEntryCacheManager.java:34) ~[restx-core-0.34.jar:na]
```

My Bootstrap component don't even use `com.stackcare.site.user.User` class.

**Comment by fcamblor** [comment]
Could you copy/paste your entire `Bootstrap` class here please ?

**Comment by fedotxxl** [comment]
>Could you copy/paste your entire Bootstrap class here please ?
It doesn't make sence

I inject few non `AutoStartable` components which internally have deep hierarchy of other non `AutoStartable` components. 

Looks like at the end of this hierarchy injected component uses `Dao` which is also used by `UserRepository` which is used by `StdBasicPrincipalAuthenticator`. 

Removing DAO injection fixes the problem

**Comment by fcamblor** [comment]
Cannot reproduce
