### ISSUE TITLE
ObjectMapper conflict in RestxStatsCollector.java

### ISSUE THREAD

**Issue by Tomsons** [restx/restx#218]
Just had an issue with `RestxStatsCollector` when creating a new Jackson `ObjectMapper` via `@Provides` in a new module, it seems like the `RestxStatsCollector` doesn't know which one to inject. 

Here is the snippet:

```
@Module
public class AppModule {

     .......

    @Provides @Named("MyObjectMapper")
    public ObjectMapper objectMapper(){

        ObjectMapper mapper = new ObjectMapper();
        SimpleModule module = new SimpleModule();
        module.addDeserializer(MyClass.class, new MyClassDeserializer());

        mapper.registerModule(module);

        return mapper;

    }
}
```

You can see the stack trace below:

```
java.lang.IllegalStateException: more than one component is available for QueryByClass{componentClass=com.fasterxml.jackson.databind.ObjectMapper[AppClassLoader]}. Please select which one you want with a more specific query. Available components are: [NamedComponent{name=Name{name='FrontObjectMapper', clazz=com.fasterxml.jackson.databind.ObjectMapper[AppClassLoader]}, priority=0, component=com.fasterxml.jackson.databind.ObjectMapper@7965a51c}, NamedComponent{name=Name{name='MyCustomObjectMapper', clazz=com.fasterxml.jackson.databind.ObjectMapper[AppClassLoader]}, priority=2147483647, component=com.fasterxml.jackson.databind.ObjectMapper@3eee3e2b}]
    at restx.factory.SatisfiedBOM.getOne(SatisfiedBOM.java:48) ~[restx-factory-0.34.jar:na]
    at restx.stats.RestxStatsCollectorFactoryMachine$1.doNewComponent(RestxStatsCollectorFactoryMachine.java:40) ~[restx-stats-admin-0.34.jar:na]
    at restx.stats.RestxStatsCollectorFactoryMachine$1.doNewComponent(RestxStatsCollectorFactoryMachine.java:12) ~[restx-stats-admin-0.34.jar:na]
    at restx.factory.StdMachineEngine.newComponent(StdMachineEngine.java:37) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory.buildAndStore(Factory.java:1219) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory.buildAndStore(Factory.java:1205) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory.buildAndStore(Factory.java:1071) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory.access$600(Factory.java:37) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory$NameQuery.doFindOne(Factory.java:604) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory$SingleQuery.doFind(Factory.java:521) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory$Query.find(Factory.java:448) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory$ClassQuery.doFind(Factory.java:662) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory$Query.find(Factory.java:448) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory$Query.findAsComponents(Factory.java:452) ~[restx-factory-0.34.jar:na]
    at restx.factory.Factory.start(Factory.java:845) ~[restx-factory-0.34.jar:na]
    at restx.RestxMainRouterFactory.build(RestxMainRouterFactory.java:450) ~[restx-core-0.34.jar:na]
    at restx.RestxMainRouterFactory.newInstance(RestxMainRouterFactory.java:70) ~[restx-core-0.34.jar:na]
    at restx.servlet.RestxMainRouterServlet.init(RestxMainRouterServlet.java:74) ~[restx-servlet-0.34.jar:na]
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:519) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.servlet.ServletHolder.doStart(ServletHolder.java:331) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:747) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:265) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1250) [jetty-webapp-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:706) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:492) [jetty-webapp-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.HandlerCollection.doStart(HandlerCollection.java:229) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:95) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.server.Server.doStart(Server.java:277) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
    at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:64) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
    at restx.server.JettyWebServer.start(JettyWebServer.java:109) [restx-server-jetty-0.34.jar:na]
    at restx.server.JettyWebServer.startAndAwait(JettyWebServer.java:114) [restx-server-jetty-0.34.jar:na]
```

**Comment by a-peyrard** [comment]
Indeed the `RestxStatsCollector` has an injection of the `ObjectMapper` without specifying the name, so there could be only one mapper in the system.
That being said I don't think its an issue, why not re-use the ObjectMapper provided by the restx library, and register to it your module ? Like this if a resource need your registered serializer, it will have it, as the resources will use the main ObjectMapper.
   
In order to register something on the main mapper, you have to use a `Customizer`. Have a look at the documentation: http://restx.io/docs/ref-factory.html#toc13
Or there is already a customizer implemented in restx, you might want to create something similar to it:
`restx.jackson.FrontObjectMapperCustomizer`  

HTH

**Comment by Tomsons** [comment]
Basically you're right, as you're getting all additional features provided by the `FrontObjectMapper` such as  the GuavaModule and the JodaTimeModule for Jackson.

One really weird thing we've experienced yesterday is that restx is also registering jackson modules annotated with the `@Component` annotation, which should handle the situation if you want to do some tricky customization with less code, but it seems that Jackson does not get into custom deserializers declared within that annotated component when you inject the `FrontObjectMapper` into another component and use it.

That being said, if you want to use another injectable `ObjectMapper` for any reason, such as avoiding altering the actual `FrontObjectMapper` with unexpected behavior or have a dedicated `ObjectMapper` with it own functionalities, creating a wrapper around the new mapper did the trick, but I don't think it's a good practice:

```
    @Provides
    public WrappedObjectMapper wrappedObjectMapper(){

        WrappedObjectMapper wrappedObjectMapper = new WrappedObjectMapper();

        // The WrappedObjectMapper has an ObjectMapper as property
        ObjectMapper mapper = wrappedObjectMapper.getObjectMapper();

        SimpleModule module = new SimpleModule();
        module.addDeserializer(MyClass.class, new MyClassDeserializer());

        mapper.registerModule(module);

        return wrappedObjectMapper;

    }
```
