### ISSUE TITLE
Failed toString() invocation on an object of type [restx.factory.Factory$4]

### ISSUE THREAD

**Issue by bt** [restx/restx#240]
Hello,

I've recently implemented RESTX into my Java application and I've been getting stack traces with the message __Failed toString() invocation on an object of type [restx.factory.Factory$4]__.

Here's the stack trace:

```
SLF4J: Failed toString() invocation on an object of type [restx.factory.Factory$4]
java.lang.StackOverflowError
	at com.google.common.collect.Iterables$6.iterator(Iterables.java:589)
	at com.google.common.collect.Iterables$8.iterator(Iterables.java:713)
	at com.google.common.collect.Iterables.toCollection(Iterables.java:337)
	at com.google.common.collect.Iterables.toArray(Iterables.java:328)
	at com.google.common.collect.Ordering.sortedCopy(Ordering.java:816)
	at restx.factory.Factory.findAllEnginesFor(Factory.java:1025)
	at restx.factory.Factory.findMachineEngineFor(Factory.java:1038)
	at restx.factory.Factory.getMachineEngineFor(Factory.java:1042)
	at restx.factory.Factory.getBillOfMaterialsFor(Factory.java:1272)
	at restx.factory.Factory.checkSatisfy(Factory.java:1257)
	at restx.factory.Factory.access$700(Factory.java:37)
	at restx.factory.Factory$Query.checkSatisfy(Factory.java:469)
	at restx.factory.Factory.checkSatisfy(Factory.java:1261)
	at restx.factory.Factory.access$700(Factory.java:37)
	at restx.factory.Factory$Query.checkSatisfy(Factory.java:469)
	at restx.factory.Factory.checkSatisfy(Factory.java:1261)
	at restx.factory.Factory.access$700(Factory.java:37)
	at restx.factory.Factory$Query.checkSatisfy(Factory.java:469)
```

And it will continue to throw the stack trace, repeating lines:

```
	at restx.factory.Factory.checkSatisfy(Factory.java:1261)
	at restx.factory.Factory.access$700(Factory.java:37)
	at restx.factory.Factory$Query.checkSatisfy(Factory.java:469)
```

I've tried to debug this issue with no solution, does anyone know what the issue is?

Thanks!

__EDIT:__
Furthermore, it seems to happen after the following line:

```
14:13:59,403  INFO Factory:488 - 006-006(96) - building Name{name='restx.activation::restx.security.RestxSessionBareFilter::RestxSessionBareFilter', clazz=java.lang.String[]} with StdMachineEngine{name=Name{name='restx.activation::restx.security.RestxSessionBareFilter::RestxSessionBareFilter', clazz=java.lang.String[]}, priority=0, boxFactory=BoundlessComponentBox.FACTORY, bom=BillOfMaterials{[]}} / SatisfiedBOM{bom=BillOfMaterials{[]}, materials={}}
```

**Comment by bt** [comment]
Alright, I seemed to have fix it.

The problem is that some classes that I created before were being cached by the factory. Because my clean task doesn't delete the `target` directory, it used those classes that were previously generated and trying to load them even though they didn't exist anymore.

The solution is to delete the target directory during the clean task.
