### ISSUE TITLE
Regression in 0.35 on Jongo id generation

### ISSUE THREAD

**Issue by fcamblor** [restx/restx#285]
We have a serious regression in released-but-not-announced-yet 0.35 version for RestX, regarding mongo id generation based on jongo

First of all, you will be encouraged by Jongo to make following steps :
- Replace deprecated `@ObjectId` annotation by `@MongoObjectId`
- Replace deprecated `@Id` annotation by `@MongoObjectId @JsonProperty("_id")` (`@JsonProperty` annotation being required only if your field as a different name than `_id`, for example you name it `id`)

Those migration steps are not impacting the regression (we encounter the regression both on "old" and "new" annotations)

I created [a branch on my repository](https://github.com/fcamblor/restx/tree/mongo-id-generation-regression) to spot this regression : [tests](https://github.com/fcamblor/restx/commit/f48e9373420c489be214fdad07b8c0ab9ac934e1) on this branch are green on 0.34 and not on 0.35.

I identified 3 cases so far :

## ✅ Using `@Id`/`@MongoId` annotation AND `ObjectId` field type

Following syntax :
```
@MongoId @JsonProperty("_id")
private ObjectId id;
```
which corresponds to following legacy syntax :
```
@Id
private ObjectId id;
```

If you're in that case, then no regression will be impacting you

## ⛔️ Using `@ObjectId @Id`/`@MongoId @MongoObjectId @JsonProperty("_id")` annotations AND `String` field type

Following syntax is currently hitting one bug :
```
@MongoId @MongoObjectId @JsonProperty("_id")
private String id;
```
which corresponds to following legacy syntax :
```
@ObjectId @Id
private String id;
```

The detailed bug seems related to `bson4jackson@2.8.0` incompatibility with `jongo@1.3.0` (see [this jongo issue](https://github.com/bguerout/jongo/issues/322) related to [this bson4jackson issue](https://github.com/michel-kraemer/bson4jackson/issues/80#issuecomment-389715005)) as we get following error :
```
ERROR restx.StdRestxMainRouter - request raised BsonSerializationException: While decoding a BSON document 4 bytes were required, but only 0 remain
org.bson.BsonSerializationException: While decoding a BSON document 4 bytes were required, but only 0 remain
```

<details><summary>Full stacktrace</summary>

```
ERROR restx.StdRestxMainRouter - request raised BsonSerializationException: While decoding a BSON document 4 bytes were required, but only 0 remain
org.bson.BsonSerializationException: While decoding a BSON document 4 bytes were required, but only 0 remain
	at org.bson.io.ByteBufferBsonInput.ensureAvailable(ByteBufferBsonInput.java:218) ~[mongo-java-driver-3.4.0.jar:na]
	at org.bson.io.ByteBufferBsonInput.readInt32(ByteBufferBsonInput.java:106) ~[mongo-java-driver-3.4.0.jar:na]
	at org.bson.BsonBinaryWriter.pipe(BsonBinaryWriter.java:304) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBEncoderAdapter.encode(DBEncoderAdapter.java:47) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBEncoderFactoryAdapter.encode(DBEncoderFactoryAdapter.java:33) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBEncoderFactoryAdapter.encode(DBEncoderFactoryAdapter.java:23) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:48) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.CompoundDBObjectCodec.encode(CompoundDBObjectCodec.java:27) ~[mongo-java-driver-3.4.0.jar:na]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:63) ~[mongo-java-driver-3.4.0.jar:na]
	at org.bson.codecs.BsonDocumentWrapperCodec.encode(BsonDocumentWrapperCodec.java:29) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.RequestMessage.addDocument(RequestMessage.java:253) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.RequestMessage.addCollectibleDocument(RequestMessage.java:219) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.InsertMessage.encodeMessageBodyWithMetadata(InsertMessage.java:73) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.RequestMessage.encodeWithMetadata(RequestMessage.java:160) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.WriteProtocol.execute(WriteProtocol.java:89) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.InsertProtocol.execute(InsertProtocol.java:68) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.InsertProtocol.execute(InsertProtocol.java:39) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.connection.DefaultServerConnection.insert(DefaultServerConnection.java:76) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.operation.InsertOperation.executeProtocol(InsertOperation.java:66) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:141) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:133) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:422) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:413) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.Mongo.execute(Mongo.java:845) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.Mongo$2.execute(Mongo.java:828) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:342) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:337) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:328) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:298) ~[mongo-java-driver-3.4.0.jar:na]
	at com.mongodb.DBCollection.insert(DBCollection.java:264) ~[mongo-java-driver-3.4.0.jar:na]
	at org.jongo.Insert.insert(Insert.java:59) ~[jongo-1.3.0.jar:na]
	at org.jongo.MongoCollection.insert(MongoCollection.java:140) ~[jongo-1.3.0.jar:na]
	at org.jongo.MongoCollection.insert(MongoCollection.java:132) ~[jongo-1.3.0.jar:na]
	at samplest.jongo.MongoResource.createObjectWithObjectIdAnnotation(MongoResource.java:75) ~[classes/:na]
	at samplest.jongo.MongoResourceRouter$2.doRoute(MongoResourceRouter.java:109) ~[classes/:na]
	at samplest.jongo.MongoResourceRouter$2.doRoute(MongoResourceRouter.java:104) ~[classes/:na]
	at restx.entity.StdEntityRoute.handle(StdEntityRoute.java:250) ~[classes/:na]
	at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[classes/:na]
	at restx.ResponseCloserFilter.handle(ResponseCloserFilter.java:28) ~[classes/:na]
	at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[classes/:na]
	at restx.CacheFilter$1.handle(CacheFilter.java:51) ~[classes/:na]
	at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[classes/:na]
	at restx.security.RestxSessionLogFilter.handle(RestxSessionLogFilter.java:43) ~[classes/:na]
	at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[classes/:na]
	at restx.security.RestxSessionCookieFilter.handle(RestxSessionCookieFilter.java:100) ~[classes/:na]
	at restx.RestxHandlerMatch.handle(RestxHandlerMatch.java:56) ~[classes/:na]
	at restx.StdRestxMainRouter.route(StdRestxMainRouter.java:153) ~[classes/:na]
	at restx.RestxMainRouterFactory$PerRequestFactoryLoader.route(RestxMainRouterFactory.java:233) [classes/:na]
	at restx.RestxMainRouterFactory$RecordingMainRouter.route(RestxMainRouterFactory.java:190) [classes/:na]
	at restx.servlet.AbstractRestxMainRouterServlet.service(AbstractRestxMainRouterServlet.java:48) [classes/:na]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) [javax.servlet-3.0.0.v201112011016.jar:na]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:669) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536) [jetty-security-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1072) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:382) [jetty-servlet-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1006) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.Server.handle(Server.java:365) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:485) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:937) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:998) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:856) [jetty-http-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240) [jetty-http-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82) [jetty-server-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628) [jetty-io-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52) [jetty-io-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543) [jetty-util-8.1.8.v20121106.jar:8.1.8.v20121106]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]
```

</details>

## ⛔️ Using `@Id`/`@MongoId @JsonProperty("_id")` annotations AND `String` field type

Following syntax is currently hitting another bug :
```
@MongoId @JsonProperty("_id")
private String id;
```
which corresponds to following legacy syntax :
```
@Id
private String id;
```

In that case, the regression is id **will be `null`** after a call to `JongoCollection.insert()`.
In 0.34 it was **NOT `null`** (id where populated).

The thing about this issue is it is completely "silent" (no error thrown), so you may not be aware of it if you migrate to 0.35 !

This issue seems related to `jongo@1.1` => `jongo@1.2` migration : https://github.com/bguerout/jongo/issues/325

**Comment by fcamblor** [comment]
Found that last case sounds related to `jongo@1.1` => `jongo@1.2` migration : https://github.com/bguerout/jongo/issues/325

**Comment by fcamblor** [comment]
Second case seems related to an incompatibility between `jongo@>=1.3.0` and `bson4jackson@>=2.8.0`, see https://github.com/bguerout/jongo/issues/322

**Comment by fcamblor** [comment]
jongo just released 2 versions early this week :
- `jongo@1.3.1` which stays on `bson4jackson@2.7.0` (and `jackson@2.7.x`). Problem is :  date deserialization error which was the cause for `bson4jackson@2.7.0` => `bson4jackson@2.8.0` upgrade will be still there
- `jongo@1.4.0` aligned over `bson4jackson@2.9.0` and `jackson@2.9.x`. It fixes error number 2 in current issue (`Using @ObjectId @Id/@MongoId @MongoObjectId @JsonProperty("_id") annotations AND String field type`). The thing is we never upgraded to `jackson@2.9.x` until now and it is not plainly tested.

My plan would be to rollback jongo/bson4jackson/jackson upgrades (see [my branch](https://github.com/fcamblor/restx/tree/mongo-id-generation-regression)) in a `restx@0.35.1` and upgrade to `jongo@1.4.0` + `bson4jackson@2.9.0` + `jackson@2.9.x` in a future `restx@0.36` which should be released quickly.

**Comment by xhanin** [comment]
Sounds like a good plan !

Le mer. 2 mai 2018 à 11:47, Frédéric Camblor <notifications@github.com> a
écrit :

**Comment by fcamblor** [comment]
@michel-kraemer fixed second issue in bson4jackson (see https://github.com/michel-kraemer/bson4jackson/issues/80) which makes @bguerout's fix in `jongo@1.4.0` useless.

It will be better to align over a future `jongo@1.4.1` (itself aligned over `bson4jackson@2.9.2` which will contain the fix) rather than keeping `jongo@1.4.0` dependency

**Comment by bguerout** [comment]
You are right. 

I'm waiting for the `bson4jackson` fixed to be released.

**Comment by bguerout** [comment]
Is there anything else needed for the future restx@0.36 ?

**Comment by fcamblor** [comment]
@bguerout Nope, not particularly

But no emergency, there was no restx release for 2 years before `v0.35` was out in Jan 2018

Our devs can wait few days/weeks for v0.36 :-)

**Comment by fcamblor** [comment]
@bguerout Hi Benoit, bson4jackson v2.9.2 has been released with the fix (https://github.com/michel-kraemer/bson4jackson/issues/80#issuecomment-390400160)

Any possibility to get a `jongo@1.4.1` release out including :
- rollback of your fix introduced in `jongo@1.4.0`
- Alignment over `bson4jackson@2.9.2` which fixes the issue

It would be very nice :-)

**Comment by bguerout** [comment]
Sorry for the late response. I going to work on this.

**Comment by bguerout** [comment]
Hello, is it possible to test your code against the latest 1.4.1-SNAPSHOT jongo version available in the oss sonatype snapshot repository ?

https://oss.sonatype.org/content/repositories/snapshots/org/jongo/jongo/1.4.1-SNAPSHOT/
