### ISSUE TITLE
Eclipse Photon 4.8 ClassCastException Annotation processor

### ISSUE THREAD

**Issue by samgabriel** [restx/restx#293]
After updating the pom to use restx 0.35 and updating the maven project. Received this error on all the files that have any annotations in the project. 
It seems the code is trying to cast the methodAnnotation.getAnnotationType().asElement()).members().getElements() to a Symbol.ClassSymbol from the com.sun.tools.javac . However eclipse does not use the default Oracle compiler. it has its own jdt compiler. this page http://restx.io/docs/ide-eclipse.html#toc6 mentions that all what needed to be done is use the maven and allow the APT but that is not working with version 0.35. This is currently working with version 0.34

`FATAL ERROR: error when processing public com.fasterxml.jackson.databind.JsonNode getAssignedAccountsByWaitTimeGroupID(restx.RestxRequest, int)  java.lang.ClassCastException: org.eclipse.jdt.internal.compiler.apt.model.TypeElementImpl cannot be cast to jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol
	at restx.annotations.processor.RestxAnnotationProcessor.createAnnotationDescriptionFrom(RestxAnnotationProcessor.java:212)
	at restx.annotations.processor.RestxAnnotationProcessor.processImpl(RestxAnnotationProcessor.java:97)
	at restx.common.processor.RestxAbstractProcessor.process(RestxAbstractProcessor.java:39)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.handleProcessor(RoundDispatcher.java:139)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.RoundDispatcher.round(RoundDispatcher.java:121)
	at org.eclipse.jdt.internal.compiler.apt.dispatch.BaseAnnotationProcessorManager.processAnnotations(BaseAnnotationProcessorManager.java:159)
	at org.eclipse.jdt.internal.apt.pluggable.core.dispatch.IdeAnnotationProcessorManager.processAnnotations(IdeAnnotationProcessorManager.java:135)`

**Comment by fcamblor** [comment]
What is your JDK version ?

I faced same issue as well while trying to use RestX 0.35+ with OpenJDK 9+, so more likely related to JDK than with eclipse compiler.

**Comment by samgabriel** [comment]
@fcamblor  The jdk that is running eclipse is jdk 10.  I agree it is a very bad idea to use this com.sun.tools classes. I glanced quickly at the code i think it can be done by registering a visitor but I am not sure.

**Comment by samgabriel** [comment]
@fcamblor  I just pushed a pull request #299  that fixes the issue in eclipse by changing to use the jdk public classes.

https://github.com/restx/restx/pull/299

**Comment by fhebuterne** [comment]
Hi,

This is fixed in latest restx release (currently 1.0.0-rc2).

You need to upgrade on restx 1.0.0-rc2 and Java 17, we plan to create an release note when 1.0.0 final version will be released.
