### ISSUE TITLE
restx-samplest tests are failing

### ISSUE THREAD

**Issue by nhumblot** [restx/restx#312]
*Jdk version:* `java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64`
*Maven version:* Maven plugin of Intellij Idea 2020.1 located in `<idea_path>/plugins/maven/lib/maven3` -> Maven 3.6.1 (core)

**Steps to reproduce:**
1. Checkout master branch (current commit: c92e983)
2. Apply workarond in #310
3. Perform a `mvn verify` on `restx-parent`

**Expected behaviour:**
Dependencies are downloaded, application is packaged, tests are launched

**Current behaviour:**
Error during `restx-samplest` tests execution:

```
Failed tests:
  AutoStartableTest.should_handle_auto_startable_in_dev_mode:31 expected:<...called: 1 started: 1[ closed: 0 instanciated: ]1 serverId: Jetty8#1...> but was:<...called: 1 started: 1[11 closed: 110 instanciated: 11]1 serverId: Jetty8#1...>
Tests in error:
  ParametersResourceSpecTest.samplest.core.ParametersResourceSpecTest » MongoTimeout
  UUIDResourceSpecTest.samplest.core.UUIDResourceSpecTest » MongoTimeout Timed o...
  SecurityResourceSpecsTest.samplest.security.SecurityResourceSpecsTest » MongoTimeout
  ValidationResourceTest.samplest.validation.ValidationResourceTest » MongoTimeout
  MongoResourceSpecsTest.objectsWithNewJongoAnnotations persistence » MongoTimeout
  MongoResourceSpecsTest.objectsWithObjectId persistence » MongoTimeout Timed ou...
  MongoResourceSpecsTest.objectsWithIdAnnotation persistence » MongoTimeout Time...
  MongoResourceSpecsTest.objectsWithObjectIdAnnotation persistence » MongoTimeout
  MongoResourceSpecsTest.samplest.jongo.MongoResourceSpecsTest » MongoTimeout Ti...
Tests run: 87, Failures: 1, Errors: 9, Skipped: 0
```

**Comment by nhumblot** [comment]
Removed my analysis and workaround statements as they are false. One thing noticed is `MongoResourceSpecsTest` works fine when executed in Intellij Idea but fails in Maven.

So my previous assumption that annotating all classes with `MongoResxSpecTestsRunner` is providing a fix only in Intelij Idea but is still failing in Maven, not a good workaround.

For `MongoResourceSpecsTest` based on the logs, I see the mongod process being launched and listening to connections.
```
[mongod output] 2020-04-13T11:47:48.550+0200 I CONTROL  [initandlisten] MongoDB starting : pid=17536 port=35031 dbpath=/tmp/embedmongo-db-dd516b03-f39b-46f3-974a-19337f63b533 64-bit host=localhost.localdomain
[mongod output] 2020-04-13T11:47:49.249+0200 I NETWORK  [initandlisten] waiting for connections on port 35031
```

When RESTX starts, it tries to connect to the mongodb database on a wrong port:
```
2020-04-13 09:47:49,357 [main            ] [          ] INFO  restx.RestxMainRouterFactory - LOADING MAIN ROUTER
2020-04-13 09:47:49,357 [main            ] [          ] INFO  restx.RestxMainRouterFactory - 
--------------------------------------
 -- RESTX >> LOAD ON REQUEST << >> CLEAN << >> TEST MODE <<
 -- for admin console,
 --   VISIT http://127.0.0.1:42735/api/@/ui/
 --
server started
using db mongodb://localhost:27017/testing-mongo-test-1586771269424-5
```

mongod is listening on `35031` (randomly selected) but RESTX tries to connect on `27017`.

Because of that, we then end up with exceptions:
```
2020-04-13 09:47:49,425 [main            ] [          ] INFO  org.mongodb.driver.cluster - Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
2020-04-13 09:47:49,431 [cluster-ClusterId{value='5e9435455507232dc24ad907', description='null'}-localhost:27017] [          ] INFO  org.mongodb.driver.cluster - Exception in monitor thread while connecting to server localhost:27017
com.mongodb.MongoSocketOpenException: Exception opening socket
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:70)
	at com.mongodb.internal.connection.InternalStreamConnection.open(InternalStreamConnection.java:128)
	at com.mongodb.internal.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:117)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connexion refusée (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at com.mongodb.internal.connection.SocketStreamHelper.initialize(SocketStreamHelper.java:64)
	at com.mongodb.internal.connection.SocketStream.initializeSocket(SocketStream.java:79)
	at com.mongodb.internal.connection.SocketStream.open(SocketStream.java:65)
	... 3 common frames omitted
```

**Comment by nhumblot** [comment]
By adding some logging statements in order to understand what is happening.

It appears that `GivenJongoCollectionSpecRuleSupplier` is instantiated only once when executing the Maven job, at the first execution of a test running with `RestxSpecTestsRunner`.

In my case, the first one was `ParametersResourceSpecTest`, which is not using `MongoRestxSpecTestsRunner`. So without an embedded Mongo being launched, the value in the settings is set to it's default value: localhost:21017, and stay like this for the whole testing suite.

Because embedded Mongo is started for every class, we must refresh these settings for every test class, I had to create a new `Factory` instance for every `RestxSpecTests` (see: https://github.com/nhumblot/restx/commit/922ec7840ea74bf6440625afad41e08d1dfc8e25)

For every `RestxSpecTestsRunner`, a `GivenJongoCollectionSpecRule` is still created. At the end of tests for a class, `tearDown()` tries to connect to a non existent Mongo database and fail. For these, we can move them to be run with `MongoRestxSpecTestsRunner` instead. It looks like the `Factory` is picking `GivenJongoCollectionSpecRule` because it is in the classpath. Does it means that if you add `restx-jongo-specs-tests` as a dependency, then `RestxSpecTestsRunner` become unusable and you need to annotate every SpecTest with it ?

I couldn't make `AutoStartableTest` work. Moving it purely to an annotated test seems impossible, because of the serverId being variable in the response so I just added an `@Ignore` on it for the moment.

All changes can be found here if someone wants a workaround: https://github.com/nhumblot/restx/commits/fix_failed_tests

Let me know if you think some of these changes are not pure workarounds and should be integrated in a pull request.
